### ISSUE TITLE
TemplateDoesNotExist at /contact/ captcha/widget_nocaptcha.html

### ISSUE THREAD

**Issue by boryskuczkowski** [maru/django-contact-form-recaptcha#1]
As in title, the fix to that seems to be adding 'captcha' to installed apps in settings.py, despite documentation clearly stating that there is no need for it.
Any thoughts?

**Comment by maru** [comment]
Yes, you're right! Sorry, I'll fix it and get back to you!

**Comment by maru** [comment]
Hello! I fixed the documentation.

You should reinstall the package and follow the instructions in https://github.com/maru/django-contact-form-recaptcha 

If you have any other problem/questions, don't hesitate to tell me!
